// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stwckvdqstcbegcjlmta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0d2NrdmRxc3RjYmVnY2psbXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNDEyNTMsImV4cCI6MjA1NjcxNzI1M30.Nl0sO6RnvrE4eDVmUSYCvTOtj5MkboYSMcObQGXdjnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);